# Generated by Django 6.0.2 on 2026-03-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_produtos/'),
        ),
    ]
